Staging/Herzon/Csharp_codebehnid/ProudSourceBeta/ProudSourceBeta/Controllers/EntrepreneurController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace ProudSourceBeta.Controllers
{
    [Authorize]
    public class EntrepreneurController : Controller
    {
        /// <summary>
        /// Private struct to make it easy to pass authentication around in this class.
        /// </summary>
        private struct EntrepreneurAuth
        {
            public bool Valid { get; set; }
            public int User_Id { get; set; }
            public int Entrepreneur_ID { get; set; }
        }

        // GET: Entrepreneur/Index/{entrepreneur_id}
        [HttpGet]
        public ActionResult Index()
        {
            EntrepreneurAuth cred = check_clientRelation();
            if (!cred.Valid)
            {
                return Redirect(@"/User/Index");
            }
            manageClient_Sessions(cred);
            Models.EntrepreneurIndexViewModel entrepreneurAccount = new Models.EntrepreneurIndexViewModel(cred.Entrepreneur_ID, User.Identity.GetUserId());
            return View(entrepreneurAccount);
        }

        [HttpGet]
        public ActionResult Projects()
        {
            EntrepreneurAuth cred = check_clientRelation();
            if (!cred.Valid)
            {
                return Redirect(@"/User/Index");
            }
            manageClient_Sessions(cred);
            Models.EntrepreneurIndexViewModel entrepreneurAccount = new Models.EntrepreneurIndexViewModel(cred.Entrepreneur_ID, User.Identity.GetUserId());
            return View(entrepreneurAccount);
        }

        // GET: Entrepreneur/Edit/{entrepreneur_id}
        [HttpGet]
        public ActionResult Edit()
        {
            EntrepreneurAuth cred = check_clientRelation();
            if(!cred.Valid)
            {
                return Redirect(@"/User/Index");
            }
            manageClient_Sessions(cred);
            Models.EntrepreneurEditViewModel entrepreneurAccount = new Models.EntrepreneurEditViewModel(cred.Entrepreneur_ID, User.Identity.GetUserId());
            return View(entrepreneurAccount);
        }

        // POST: Entrepreneur/Edit/{entrepreneur_id}
        [HttpPost]
        public ActionResult Edit(Models.EntrepreneurEditViewModel updateModel, HttpPostedFileBase update_Profile_Image)
        {
            EntrepreneurAuth cred = check_clientRelation();
            if (!cred.Valid)
            {
                return Redirect("/User/Index");
            }
            try
            {
                // code to process a posted image file.
                byte[] picture_bytes = null;
                if (ModelState.IsValid)
                {
                    if (update_Profile_Image != null)
                    {
                        if (update_Profile_Image.ContentLength > 0)
                        {
                            int MaxContentLength = 1024 * 1024 * 3;
                            string[] AllowedFileExtensions = new string[] { ".jpg", ".gif", ".png", ".pdf" };

                            if (!AllowedFileExtensions.Contains(update_Profile_Image.FileName.Substring(update_Profile_Image.FileName.LastIndexOf('.'))))
                            {
                                ModelState.AddModelError("profile_picture", "Please only use file types: " + string.Join(", ", AllowedFileExtensions));
                            }
                            else if (update_Profile_Image.ContentLength > MaxContentLength)
                            {
                                ModelState.AddModelError("profile_picture", string.Format("Your file is too large, maximum file size is: {0} Bytes.", MaxContentLength));
                            }
                            else
                            {
                                picture_bytes = new byte[update_Profile_Image.ContentLength];
                                update_Profile_Image.InputStream.Read(picture_bytes, 0, update_Profile_Image.ContentLength);
                            }
                        }
                    }
                }

                Models.EntrepreneurEditViewModel authModel = new Models.EntrepreneurEditViewModel(cred.Entrepreneur_ID, User.Identity.GetUserId());
                authModel.Name = updateModel.Name;
                authModel.Profile_Public = updateModel.Profile_Public;
                authModel.Profile_Picture = picture_bytes;
                authModel.updateEntrepreneur();
            }
            catch (Exception e)
            {
                System.Diagnostics.Debug.WriteLine(e.Message);
                return View();
            }
            return Redirect("/User/Index/");
        }

        // GET: Entrepreneur/createProject/{enrepreneur_id}
        [HttpGet]
        public ActionResult createProject()
        {
            EntrepreneurAuth cred = check_clientRelation();
            if(!cred.Valid)
            {
                Redirect("/User/Index"); // kick out of entrepreneur control to the user control.
            }
            manageClient_Sessions(cred);
            Models.EntrepreneurCreateProjectViewModel entrepreneurAccount = new Models.EntrepreneurCreateProjectViewModel(cred.Entrepreneur_ID, User.Identity.GetUserId());
            return View(entrepreneurAccount);
        }

        // POST: Entrepreneur/createProject/{entrepreneur_id}
        [HttpPost]
        public ActionResult createProject(Models.EntrepreneurCreateProjectViewModel newProject)
        {
            EntrepreneurAuth cred = check_clientRelation();
            if(!cred.Valid)
            {
                Redirect("/User/Index"); // kick out of entrepreneur control to the user control.
            }
            Models.EntrepreneurCreateProjectViewModel authenticated_newProject = new Models.EntrepreneurCreateProjectViewModel(cred.Entrepreneur_ID, User.Identity.GetUserId());
            authenticated_newProject.Name = newProject.Name;
            authenticated_newProject.Description = newProject.Description;
            authenticated_newProject.Investment_Goal = newProject.Investment_Goal;
            int newPRoject_Id = authenticated_newProject.createProject();
            if(newPRoject_Id == 0)
            {
                // TODO: return error to client user on page.
                ModelState.AddModelError("", "Project account not created.");
                return View(newProject);
            }
            return Redirect(string.Format("/Project/Index/{0}", newPRoject_Id));
        }

        /// <summary>
        /// Method that displays data for clients who are not this account owner.
        /// </summary>
        /// <returns></returns>
        // GET: Entrepreneur/Details/{entrepreneur_id}
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            Models.EntrepreneurIndexViewModel entrepreneurModel;
            if (User.Identity.GetUserId() != null)
            {
                SessionUserAccessor session = get_SessionIDs();
                if (session.Entrepreneur_ID > 0)
                {
                    entrepreneurModel = new Models.EntrepreneurIndexViewModel(id, User.Identity.GetUserId(), session.Entrepreneur_ID);
                    if (entrepreneurModel.Profile_Public)
                        return View(entrepreneurModel);
                    else
                        return Redirect("/Search/Index");
                }
                else if (session.Investor_ID > 0)
                {
                    entrepreneurModel = new Models.EntrepreneurIndexViewModel(id, User.Identity.GetUserId(), session.Investor_ID);
                    if (entrepreneurModel.Profile_Public)
                        return View(entrepreneurModel);
                    else
                        return Redirect("/Search/Index");
                }
            }
            else
            {
                entrepreneurModel = new Models.EntrepreneurIndexViewModel();
                entrepreneurModel._get_EntrepreneurData(id);
                if (entrepreneurModel.Profile_Public)
                    return View(entrepreneurModel);
            }
            return Redirect("/Search/Index");
        }

        /// <summary>
        /// Method that accepts messages and likes from clients who are not the account owner.
        /// </summary>
        /// <param name="placeholder"></param>
        /// <returns></returns>
        // POST: Entrepreneur/Details/{entrepreneur_id}
        [HttpPost]
        [Authorize]
        public ActionResult Details(int id, string Entrepreneur_Message)
        {
            Models.EntrepreneurIndexViewModel entrepreneurModel = new Models.EntrepreneurIndexViewModel(id, User.Identity.GetUserId());
            SessionUserAccessor session = get_SessionIDs();
            if (session.Entrepreneur_ID > 0)
                entrepreneurModel.message_Entrepreneur(id, session.Entrepreneur_ID, 4, Entrepreneur_Message);
            else if (session.Investor_ID > 0)
                entrepreneurModel.message_Entrepreneur(id, session.Investor_ID, 3, Entrepreneur_Message);
            else
                entrepreneurModel.message_Entrepreneur(id, entrepreneurModel.User_Id, 1, Entrepreneur_Message);
            return View(entrepreneurModel);
        }

        /// <summary>
        /// Private method that checks to make sure client user is actually related to this account.
        /// </summary>
        /// <returns></returns>
        private EntrepreneurAuth check_clientRelation()
        {
            EntrepreneurAuth cred = new EntrepreneurAuth { };
            string[] holding = Request.RawUrl.Split(new char[] { '/' }).ToArray<string>();
            int Entrepreneur_Id = 0;
            try
            {
                Entrepreneur_Id = Convert.ToInt32(holding[holding.Count<string>() - 1]);
            }
            catch
            {

Staging/Herzon/Csharp_codebehnid/ProudSourceBeta/ProudSourceBeta/Views/Entrepreneur/Details.cshtml
@model ProudSourceBeta.Models.EntrepreneurIndexViewModel

<h2>Entrepreneur Details</h2>

<hr />

<div class="container">
    <dl class="dl-horizontal">

        <dt class="profile-words">
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class="profile-words">
            @Html.DisplayNameFor(model => model.Verified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Verified)
        </dd>

        <dt class="profile-words">Entrepreneur Image</dt>

        <dd>
            <div class="profile-image">

                @{ var imgSrc = "/Images/emptyProfile.png";
                    if (Model.Profile_Picture != null)
                    {
                        var base64 = Convert.ToBase64String(Model.Profile_Picture);
                        imgSrc = string.Format("data:image/gif;base64,{0}", base64);
                    }
                }

                <img id="profile-image" src="@imgSrc" />

            </div>
        </dd>

    </dl>
</div>

<hr />

@if(Model.Entrepreneur_ID != Model.Viewer_ID)
{
    @*if(IsPost)
    {
        <div class="container">
            <p class="template-words">Your message has been posted</p>
        </div>
    }

    if (!IsPost && Model.User_Id > 0)
    {
        <div class="container">
            <div class="form">
                <form id="message-entrepreneur" method="post">
                    <div class="col-md-10">

                        <textarea form="message-entrepreneur" name="Entrepreneur_Message" class="input-group-lg"></textarea>

                    </div>

                    <div class="col-md-offset-2 col-md-10">

                        <input type="submit" value="message" class="btn btn-default" />

                    </div>
                </form>

            </div>
        </div>
        }
    }*@
<p>
    <a href="/Search/Index">Search the ProudSource community</a>
</p>

Staging/Herzon/Csharp_codebehnid/ProudSourceBeta/ProudSourceBeta/Views/Entrepreneur/Edit.cshtml
@model ProudSourceBeta.Models.EntrepreneurEditViewModel

@{
    ViewBag.Title = "Edit";
}

<h2 class="template-header">Edit Entrepreneur Details</h2>


@using (Html.BeginForm("Edit", "Entrepreneur", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.Entrepreneur_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Entrepreneur_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Entrepreneur_ID, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profile_Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="update_Profile_Image" type="file" name="update_Profile_Image" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profile_Public, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Profile_Public)
                    @Html.ValidationMessageFor(model => model.Profile_Public, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Image_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Image_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Image_ID, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { Model.Entrepreneur_ID })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Staging/Herzon/Csharp_codebehnid/ProudSourceBeta/ProudSourceBeta/Views/Entrepreneur/Index-bak.cshtml
@model ProudSourceBeta.Models.EntrepreneurIndexViewModel

<h2>Entrepreneur Account</h2>

<div class= "title-container"> </div>

<div class="container">
    
    <hr />
    <dl class="dl-horizontal">

        <dt class="profile-header">
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class="profile-header">
            @Html.DisplayNameFor(model => model.Profile_Picture )
        </dt>

        <dd>

            <div class="profile-image">
                
                @{ var imgSrc = "/Images/emptyProfile.png";
                    if (Model.Profile_Picture != null)
                    {
                        var base64 = Convert.ToBase64String(Model.Profile_Picture);
                        imgSrc = string.Format("data:image/gif;base64,{0}", base64);
                    }
                }

                <img id="profile-image" src="@imgSrc" />

            </div>

        </dd>

        <dt class="profile-header">
            @Html.DisplayNameFor(model => model.Profile_Public)
        </dt>

        <dd class="profile-header">
            @Html.DisplayFor(model => model.Profile_Public)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Verified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Verified)
        </dd>

    </dl>

    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Entrepreneur_ID }) 
        |
        <a href="/User/Index/">Back to List</a>
    </p>

    <hr />

    <h2>Project Accounts</h2>

    <p>
        @Html.ActionLink("Create New Project", "createProject", new { id = Model.Entrepreneur_ID })
    </p>

    @if (Model.Projects.Count > 0)
    {

    <table id="project-results" class="table-hover table-responsive">

        <tr>

            <th class="col-sm-4">Project Name</th>

            <th class="col-sm-4">Project Public</th>

        </tr>
        @foreach (System.Data.DataRow item in Model.Projects)
        {
            <tr>

                <td class="col-sm-4"><a href="@string.Format("/Project/Index/{0}", item["Project_ID"])">
                        @item["Name"].ToString()
                    </a>
                </td>

                <td class="col-sm-4">
                    @{ string isPublic = "";
                        if (item["Profile_Public"].ToString() == "True")
                        {
                            isPublic = "Yes";
                        }
                        else
                        {
                            isPublic = "No";
                        }
                    }
                    @isPublic
                </td>

            </tr>
        }

    </table>

    }

    @if(Model.Projects.Count < 1)
    {
        <p class="template-words">You have no projects associated with this account, perhaps you should make one.</p>
    }

</div>

Staging/Herzon/Csharp_codebehnid/ProudSourceBeta/ProudSourceBeta/Views/Entrepreneur/Index.cshtml
@model ProudSourceBeta.Models.EntrepreneurIndexViewModel

<link href="~/Content/Shared/Shared.css" rel="stylesheet" type="text/css" />
<link href="~/Content/Entrepreneur/index.css" rel="stylesheet" type="text/css" />

<script>
    function createNewProject() {
        location.href = '@string.Format("/Entrepreneur/createProject/{0}", Model.Entrepreneur_ID)'
    }
</script>

<div class="title-container">
    <div class="title">
        Projects
    </div>
</div>

<div id="container">

        @*<div class="data-container bordered-grey">

            <div style="float: left;">
                @{ var imgSrc = "/Images/emptyProfile2.jpg";
                    if (Model.Profile_Picture != null)
                    {
                        var base64 = Convert.ToBase64String(Model.Profile_Picture);
                        imgSrc = string.Format("data:image/gif;base64,{0}", base64);
                    }
                }
                <img class="circular profile-image" src="@imgSrc" />
            </div>

            <div class="account-title" style="">
                <b>Entrepreneur Profile</b>
            </div>

            <div style="clear: left"> </div>

            <div class="data-title">
                <b>Name:</b>
            </div>
            <div class="data">
                @Html.DisplayFor(model => model.Name)
            </div>
            <br />

            <button class="data flat-button flat-button-small green" onclick="location.href='@string.Format("/Entrepreneur/Edit/{0}", Model.Entrepreneur_ID)'">
                Edit Profile
            </button>

        </div>*@



        @if (Model.Projects.Count == 0)
        {
            <div class="data-container bordered-grey center" style="">
                <div class="fill-center-text" style="margin: auto">
                    <b>You have no projects!</b>
                </div>

                <button onclick="createNewProject()" class="flat-button blue"> Create New Project!</button>
            </div>
        }
        else
        {
                <table class="table table-hover" style="text-align: left; font-size: 200%; width: 100%">

                    <tbody>
                        @* Insert data into table from projects array *@
                        @foreach (System.Data.DataRow project in Model.Projects)
                        {
                            <div class="project-row">
                                <div class="title">
                                    @project["Name"]
                                </div>

                                <div class="title">
                                    Account Balance : @project["Project_Balance"]
                                </div>

                                <button onclick="(function go() { window.location = '@string.Format("/Project/Details/{0}", project["Project_ID"])' })()" class="flat-button flat-button-small green ent-project-btn" style="float: right;">
                                    View
                                </button>

                                <button onclick="(function go() { window.location = '@string.Format("/Project/Index/{0}", project["Project_ID"])' })()" class="flat-button flat-button-small blue ent-project-btn" style="float: right;">
                                    Edit
                                </button>
                            </div>
                        }

                    </tbody>
                </table>

                <br />

                <div class="container" style="text-align: center">
                    <button onclick="createNewProject()" class="flat-button large-btn blue"> Create New Project!</button>
                </div>

                




        }

</div>

Staging/Herzon/Csharp_codebehnid/ProudSourceBeta/ProudSourceBeta/Views/Entrepreneur/createProject.cshtml
@model ProudSourceBeta.Models.EntrepreneurCreateProjectViewModel

@{
    ViewBag.Title = "Project Creation";
}

<h2 class="template-header">New Project</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Investment_Goal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Investment_Goal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Investment_Goal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}