Staging/Herzon/Csharp_codebehnid/ProudSourcePrime/ProudSourcePrime/Controllers/IOController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProudSourcePrime.Controllers
{
    [Authorize]
    public class IOController : Controller
    {
        /// <summary>
        /// GET IO/Download/{document_Id}
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [AllowAnonymous]
        [HttpGet]
        public ActionResult Download(int id)
        {
            Dictionary<string, string> documentDict = new Models.DocumentFileModel().DownloadFile(id);
            if (documentDict.Keys.Count > 0)
            {
                System.Net.Mime.ContentDisposition cd = new System.Net.Mime.ContentDisposition
                {
                    FileName = documentDict["File_Name"],
                    Inline = false,
                };
                Response.AppendHeader("Content-Disposition", cd.ToString());
                return File(Convert.FromBase64String(documentDict["Base64_Encoded_File"]), documentDict["Mime_Type"]);
            }
            else
            {
                return Redirect("/Error/404");
            }
        }

        [HttpPost]
        public JsonResult DeleteLink(int id)
        {
            bool status = false;
            string exception_message = string.Empty;
            string details = string.Empty;
            try
            {
                System.IO.Stream req = Request.InputStream;
                req.Seek(0, System.IO.SeekOrigin.Begin);
                string json = new System.IO.StreamReader(req).ReadToEnd();
                string[] parameters = json.Split(new string[] { "&" }, StringSplitOptions.None);
                Dictionary<string, string> dictionary = new Dictionary<string, string>();
                for (int i = 0; i < parameters.Count(); i++)
                {
                    string[] key_and_arg = parameters[i].Split(new string[] { "=" }, StringSplitOptions.None);
                    dictionary.Add(key_and_arg[0], key_and_arg[1]);
                }
                status = new ServiceReference1.Service1Client().delete_Link(id, int.Parse(dictionary["Profile_Id"]), int.Parse(dictionary["Profile_Type_Id"]));
            }
            catch (Exception e)
            {
                exception_message = e.Message;
                details = e.InnerException.Message;
            }
            if (status)
            {
                return Json(new { success = true });
            }
            else
            {
                return Json(new { success = false, code = exception_message, message = details });
            }
        }

        [HttpPost]
        public JsonResult DeleteImage()
        {
            bool status = false;
            string exception_message = string.Empty;
            string details = string.Empty;
            try
            {
                System.IO.Stream req = Request.InputStream;
                req.Seek(0, System.IO.SeekOrigin.Begin);
                string json = new System.IO.StreamReader(req).ReadToEnd();
                string[] parameters = json.Split(new string[] { "=" }, StringSplitOptions.None);
                if(parameters.Length == 2 && parameters[0] == "Image_Id")
                {
                    status = new ServiceReference1.Service1Client().delete_Image(int.Parse(parameters[1]));
                }
            }
            catch (Exception e)
            {
                exception_message = e.Message;
                details = e.InnerException.Message;
            }
            if(status)
            {
                return Json(new { success = true });
            }
            else
            {
                if(string.IsNullOrEmpty(exception_message))
                {
                    exception_message = "Failed to delete the image";
                }
                return Json(new { success = false, code = exception_message, message = details });
            }
        }

        [HttpPost]
        public JsonResult DeleteDocument()
        {
            bool status = false;
            string exception_message = string.Empty;
            string details = string.Empty;
            try
            {
                System.IO.Stream req = Request.InputStream;
                req.Seek(0, System.IO.SeekOrigin.Begin);
                string json = new System.IO.StreamReader(req).ReadToEnd();
                string[] parameters = json.Split(new string[] { "=" }, StringSplitOptions.None);
                if (parameters.Length == 2 && parameters[0] == "Document_Id")
                {
                    status = new ServiceReference1.Service1Client().delete_Document(int.Parse(parameters[1]));
                }
            }
            catch (Exception e)
            {
                exception_message = e.Message;
                details = e.InnerException.Message;
            }
            if (status)
            {
                return Json(new { success = true });
            }
            else
            {
                if (string.IsNullOrEmpty(exception_message))
                {
                    exception_message = "Failed to delete the document";
                }
                return Json(new { success = false, code = exception_message, message = details });
            }
        }

        [HttpPost]
        public ActionResult UploadImage(Models.ImageFileModel imageModel, HttpPostedFileBase image_upload)
        {
            string exception_message = string.Empty;
            string details = string.Empty;
            try
            {
                if (image_upload != null && image_upload.ContentLength > 0)
                {
                    int MaxContentLength = 1024 * 1024 * 3;
                    string[] AllowedFileExtensions = new string[] { ".jpg", ".gif", ".png", ".pdf" };

                    if (!AllowedFileExtensions.Contains(image_upload.FileName.Substring(image_upload.FileName.LastIndexOf('.'))))
                    {
                        //ModelState.AddModelError("upload_Image", "Please only use file types: " + string.Join(", ", AllowedFileExtensions));
                        exception_message += "Please only use file types: " + string.Join(", ", AllowedFileExtensions);
                        details += "File was type: " + image_upload.FileName.Substring(image_upload.FileName.LastIndexOf('.'));
                    }
                    else if (image_upload.ContentLength > MaxContentLength)
                    {
                        //ModelState.AddModelError("upload_Image", string.Format("Your file is too large, maximum file size is: {0} Bytes.", MaxContentLength));
                        exception_message += string.Format("Your file is too large, maximum file size is: {0} Bytes.", MaxContentLength);
                        details += "File is too large";
                    }
                    else
                    {
                        byte [] picture_bytes = new byte[image_upload.ContentLength];
                        image_upload.InputStream.Read(picture_bytes, 0, image_upload.ContentLength);
                        imageModel.ImageData = picture_bytes;
                        imageModel.UploadImage();
                    }
                }
            }
            catch (Exception e)
            {

            }
            if (!string.IsNullOrEmpty(exception_message))
            {
                return Json(new { success = false, code = exception_message, message = details });
            }
            else
            {
                return Redirect(Request.UrlReferrer.ToString());
            }
        }

        [HttpPost]
        public ActionResult UpdateImage(Models.ImageFileModel imageModel, HttpPostedFileBase image_update)
        {
            try
            {
                if (image_update != null && image_update.ContentLength > 0)
                {
                    int MaxContentLength = 1024 * 1024 * 3;
                    string[] AllowedFileExtensions = new string[] { ".jpg", ".gif", ".png", ".pdf" };

                    if (!AllowedFileExtensions.Contains(image_update.FileName.Substring(image_update.FileName.LastIndexOf('.'))))
                    {
                        ModelState.AddModelError("update_Image", "Please only use file types: " + string.Join(", ", AllowedFileExtensions));
                    }
                    else if (image_update.ContentLength > MaxContentLength)
                    {
                        ModelState.AddModelError("update_Image", string.Format("Your file is too large, maximum file size is: {0} Bytes.", MaxContentLength));
                    }
                    else
                    {
                        byte[] picture_bytes = new byte[image_update.ContentLength];
                        image_update.InputStream.Read(picture_bytes, 0, image_update.ContentLength);
                        imageModel.ImageData = picture_bytes;
                        imageModel.UpdateImage();
                    }
                }
            }
            catch (Exception e)
            {

            }
            return Redirect(Request.UrlReferrer.ToString());
        }

        [HttpPost]
        public ActionResult UploadDocument(Models.DocumentFileModel documentModel, HttpPostedFileBase document_upload)
        {
            try
            {
                byte[] hold = new byte[document_upload.ContentLength];
                document_upload.InputStream.Read(hold, 0, document_upload.ContentLength);
                documentModel.FileName = document_upload.FileName;
                documentModel.MimeType = document_upload.ContentType;
                documentModel.DocumentData = hold;
                documentModel.UploadFile();
            }
            catch (Exception e)
            {

            }
            return Redirect(Request.UrlReferrer.ToString());
        }

        [HttpPost]

Staging/Herzon/Csharp_codebehnid/ProudSourcePrime/ProudSourcePrime/Views/IO/_UpdateDocument.cshtml
@model ProudSourcePrime.Models.DocumentFileModel


@using (Html.BeginForm("UploadDocument", "IO", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @*@Html.AntiForgeryToken()*@
    <hr />
    <h4>Update document</h4>
    <div class="form-horizontal">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.Document_Id)
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.IsProject)
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.Profile_Id)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DocumentData, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="document_update" type="file" name="document_update" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Staging/Herzon/Csharp_codebehnid/ProudSourcePrime/ProudSourcePrime/Views/IO/_UpdateImage.cshtml
@model ProudSourcePrime.Models.ImageFileModel


@using (Html.BeginForm("UpdateImage", "IO", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @*@Html.AntiForgeryToken()*@
    <hr />
    <h4>Update an image</h4>
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.HiddenFor(model => model.Image_Id)
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.Profile_Id)
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.IsProject)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageData, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="update_Image" type="file" name="image_update" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Staging/Herzon/Csharp_codebehnid/ProudSourcePrime/ProudSourcePrime/Views/IO/_UploadDocument.cshtml
@model ProudSourcePrime.Models.DocumentFileModel


@using (Html.BeginForm("UploadDocument", "IO", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="col-sm-offset-1">
        @*@Html.AntiForgeryToken()*@
        <h4>Upload a document</h4>
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.HiddenFor(model => model.IsProject)
            </div>

            <div class="form-group">
                @Html.HiddenFor(model => model.Profile_Id)
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DocumentData, htmlAttributes: new { @class = "control-label col-md-4" })
                <div class="col-md-offset-2 col-md-6">
                    <label class="btn btn-default" >
                        <input id="document_upload" type="file" name="document_upload" />
                    </label>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Upload" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Staging/Herzon/Csharp_codebehnid/ProudSourcePrime/ProudSourcePrime/Views/IO/_UploadImage.cshtml
@model ProudSourcePrime.Models.ImageFileModel


@using (Html.BeginForm("UploadImage", "IO", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @*@Html.AntiForgeryToken()*@
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.Profile_Id)
        @Html.HiddenFor(model => model.IsProject)

        <div class="form-group">
            @Html.LabelFor(model => model.ImageData, htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-offset-2 col-md-6">
                <span class="btn btn-default" >
                    <input id="upload_Image" type="file" name="image_upload" />
                </span> 
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Upload" class="btn btn-default" />
            </div>
        </div>
    </div>


}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Staging/Herzon/Csharp_codebehnid/ProudSourcePrime/ProudSourcePrime/Views/IO/_UploadLink.cshtml
@model ProudSourcePrime.Models.LinkModel

@using (Html.BeginForm("UploadLink", "IO", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <dic class="col-sm-offset-1">
        @*@Html.AntiForgeryToken()*@
        <h4>Upload Link</h4>
        <div id="beta-test-info" style="background-color : #80bfff; color : white; border-color : lightgray; border-width : 1px; border-radius : 25px; text-align : center;">
            <p>Too get the imbed to render properly please use the "src" imbbed link generetaed by YouTube and Vimeo when sharing a video.</p>
            <br />
            <p>Do not use the raw URL in your browser, if you want the video to render for people viewing your profile.</p>
            <br />
            <p>You can do this by clicking on share or embed and copy and pasting the link.</p>
        </div>
        <div class="form-horizontal">
            <div class="form-group">
                <input type="hidden" name="Profile_Id" value="@Model.Profile_Id" />
            </div>

            <div class="form-group">
                <input type="hidden" name="Is_Project" value="@Model.Is_Project.ToString()" />
            </div>

            @Html.ValidationMessage("Profile_Id_NULL", new { @class = "text-danger" })
            @Html.ValidationMessage("Is_Project_NULL", new { @class = "text-danger" })

            <div class="form-group row">
                <label class="control-label col-md-4">Select Link Type</label>
                <div class="col-md-8 dropdown">
                    @Html.DropDownListFor(x => x.SelectedOption, Model.SelectOptions)
                </div>
                @Html.ValidationMessage("Link_Type_Null", new { @class = "text-danger" })
            </div>

            <div class="form-group row">
                <label class="control-label col-md-4">Link</label>
                <div class="col-md-8">
                    <input class="form-control text-box single-line"
                           id="Link"
                           name="Link"
                           type="text" />
                </div> 
                @Html.ValidationMessage("Link_NULL", new { @class = "text-danger" })
            </div>

            <div class="form-group row">
                <label class="control-label col-md-4">Friendly Descriptor</label>
                <div class="col-md-8">
                    <input class="form-control text-box single-line"
                           id="FriendlyName" 
                           name="FriendlyName"
                           type="text" />
                </div> 
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Upload" class="btn btn-default" />
                </div>
            </div>
        </div>
    </dic>
}